name: Latest blog post workflow
on:
    schedule:
        - cron: '0 * * * *'
    workflow_dispatch:
permissions:
    contents: write
jobs:
    update-readme-with-blog:
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Update Qiita posts
              uses: gautamkrishnar/blog-post-workflow@v1
              with:
                max_post_count: "4"
                feed_list: "https://qiita.com/revsystem/feed"
                skip_commit: true
            - name: Update Note posts
              uses: gautamkrishnar/blog-post-workflow@v1
              with:
                comment_tag_name: "NOTE"
                max_post_count: "4"
                feed_list: "https://note.com/revsystem/rss"